import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_urdu': {
          "Whatsapp":"واٹس آپ",
          "default": "پہلے سے طے شدہ",
          'Language Options': "زبان کے اختیارات",
          'Privacy Policy': "رازداری کی پالیسی",
          "Feedback": "فیڈ بیک",
          'Help': "مدد ",
          "Sync To Gallery": "گیلری سے مطابقت پذیری کریں",
          "General Settings": "عام سیٹنگز",
          "Yes": "ہاں ",
          "No": "نہیں ",
          'to exit?': "باہر نکلنا؟",
          'Are you sure want': 'کیا آپ واقعی چاہتے ہیں',
          "Cleared cookies": "کوکیز کو صاف کیا۔",
          "Cache Cleared": "کیشے صاف ہو گیا۔",
          "Browser History Cleared": "براؤزر کی سرگزشت صاف کر دی گئی۔",
          "Clear cookies": "کوکیز صاف کریں۔",
          "Finish": "ختم کریں",
          "Next": "آگے جائیں",
          "Finished": "مکمل",
          "How to Download": "ڈاؤنلوڈ کیسے کریں",
          "No History": "کوئی تاریخ نہیں۔",
          "3D": "تھری ڈی",
          "Minimalism": "منیملزم",
          "City": "شہر",
          "Cars": "کاریں",
          "Animals": "جانور",
          "Anime": "آنیمی",
          "Trending": "ٹرینڈنگ",
          "Flowers": "پھول",
          "Saved": "محفوظ کردہ",
          "Videos": "ویڈیوز",
          "Images": "تصاویر",
          "Enter Url here": "یہاں یو آر ایل درج کریں۔",
          "Search": "تلاش کریں۔",
          "Enter user name or paste profile URL":
              "صارف کا نام ڈالیں یا یو آر ایل  چسپاں کریں",
          "AD": "اشتہار",
          "Video Download": "ویڈیو ڈاؤن لوڈ",
          "Paste": "چسپاں کریں۔",
          "Direct Link Downloader": "ڈائریکٹ لنک ڈاؤنلوڈر",
          "Vimeo": "ویمیو",
          "TikTok": "ٹک ٹاک",
          "Twitter / X": "ٹویٹر / ایکس",
          "Instagram": "انسٹاگرام",
          "Facebook": "فیس بک",
          "Social Sites Downloader": "سوشل سائٹس ڈاؤنلوڈر",
          "Search Engine": "سرچ انجن",
          "/storage/emulated/0/VideoDownloader/Download":
              "/storage/emulated/0/VideoDownloader/Download",
          "Download location": "مقام ڈاؤن لوڈ کریں۔",
          "Clear browser history": "براؤزر کی تاریخ صاف کریں۔",
          "Clear Cache": "کیشے صاف کریں۔",
          "Google": "گوگل",
          "Recommended": "تجویز کردہ",
          "Save your passwords": "اپنے پاس ورڈ محفوظ کریں۔",
          "off": "بند",
          "on": "آن",
          "Block Ads": "اشتہارات کو مسدود کریں۔",
          "Browser": "براؤزر",
          "Download with Wi-Fi only when turned on":
              "صرف آن ہونے پر Wi-Fi کے ساتھ ڈاؤن لوڈ کریں۔",
          "Settings": "ترتیبات",
          "Download": "ڈاؤن لوڈ کریں",
          "Data Saving Mode": "ڈیٹا سیونگ موڈ",
          "Tab": "ٹیب",
          "Progress": "پیش رفت",
          "Folder": "فولڈر",
          "Video Downloader": "ویڈیو ڈاؤنلوڈر",
          "Continue": "جاری رہے",
          "Select Your Language": "اپنی زبان منتخب کریں۔",
          "Search or paste profile URL": "پروفائل URL تلاش کریں یا پیسٹ کریں۔",
          "Download Story, Post & Video": "کہانی، پوسٹ ڈاؤن لوڈ کریں۔",
          "WhatsApp Status Downloader": "واٹس ایپ اسٹیٹس ڈاؤنلوڈر",
          "Download Whatsapp Stories & Status":
              "واٹس ایپ کی کہانیاں ڈاؤن لوڈ کریں۔",
          "Wallpaper Downloader": "وال پیپر ڈاؤنلوڈر",
          "Download Varity of Wallpapers":
              "مختلف قسم کے وال پیپر ڈاؤن لوڈ کریں۔",
          "Remove Ads": "اشتہارات کو ہٹا دیں۔",
          "Download everything without Ads":
              "اشتہارات کے بغیر سب کچھ ڈاؤن لوڈ کریں۔"
        },
        'en_afrikan': {
            "Whatsapp":"Whatsapp",
          "default": "verstek",
          "Language Options": "Taalopsies",
          'Privacy Policy': "Privaatheidsbeleid",
          "Feedback": "Terugvoer",
          'Help': "Help",
          "Sync To Gallery": "Sinkroniseer na galery",
          "General Settings": "Algemene instellings",
          "Yes": "ja",
          "No": "Nee",
          'to exit?': "om uit te gaan?",
          'Are you sure want': 'Is jy seker wil',
          "Cleared cookies": "Het koekies uitgevee",
          "Cache Cleared": "Kas is skoongemaak",
          "Browser History Cleared": "Blaaiergeskiedenis uitgevee",
          "Clear cookies": "Vee koekies uit",
          "Trending": "Trending",
          "Finish": "Voltooi",
          "Next": "Volgende",
          "Finished": "Klaar",
          "How to Download": "Hoe om af te laai",
          "No History": "Geen geskiedenis nie",
          "3D": "3D",
          "Minimalism": "Minimalisme",
          "City": "Stad",
          "Cars": "Motors",
          "Animals": "Diere",
          "Anime": "Anime",
          "Flowers": "Blomme",
          "Saved": "Gestoor",
          "Videos": "Video's",
          "Images": "Beelde",
          "Enter Url here": "Voer URL hier in",
          "Search": "Soek",
          "Enter user name or paste profile URL":
              "Voer gebruikernaam in of plak profiel-URL",
          "AD": "AD",
          "Video Download": "Video aflaai",
          "Paste": "Plak",
          "Direct Link Downloader": "Direkte skakel aflaaier",
          "Vimeo": "Vimeo",
          "TikTok": "TikTok",
          "Twitter / X": "Twitter / X",
          "Instagram": "Instagram",
          "Facebook": "Facebook",
          "Social Sites Downloader": "Aflaaier vir sosiale werwe",
          "Search Engine": "Soek-masjien",
          "/storage/emulated/0/VideoDownloader/Download":
              "/storage/emulated/0/VideoDownloader/Download",
          "Download location": "Laai ligging af",
          "Clear browser history": "Vee blaaiergeskiedenis uit",
          "Clear Cache": "Vee kas uit",
          "Google": "Google",
          "Recommended": "Aanbeveel",
          "Save your passwords": "Stoor jou wagwoorde",
          "off": "af",
          "on": "aan",
          "Block Ads": "Blokkeer advertensies",
          "Browser": "Blaaier",
          "Download with Wi-Fi only when turned on":
              "Laai slegs af met Wi-Fi wanneer dit aangeskakel is",
          "Settings": "Instellings",
          "Download": "Aflaai",
          "Data Saving Mode": "Databesparingsmodus",
          "Tab": "Tab",
          "Progress": "Vordering",
          "Folder": "Folder",
          "Video Downloader": "Video-aflaaier",
          "Continue": "Aanhou",
          "Select Your Language": "Kies jou taal",
          "Search or paste profile URL": "Soek of plak profiel-URL",
          "Download Story, Post & Video": "Laai Story, Post af",
          "WhatsApp Status Downloader": "WhatsApp Status Aflaaier",
          "Download Whatsapp Stories & Status": "Laai Whatsapp Stories af",
          "Wallpaper Downloader": "Muurpapier-aflaaier",
          "Download Varity of Wallpapers": "Laai Verskeidenheid agtergronde af",
          "Remove Ads": "Verwyder advertensies",
          "Download everything without Ads": "Laai alles af sonder advertensies"
        },
        'en_arabic': {
          "Whatsapp":"واتس اب",
          "default": "افتراضي",
          "Language Options": "خيارات اللغة",
          'Privacy Policy': "سياسة الخصوصية",
          "Feedback": "التعليقات",
          'Help': "مساعدة ",
          "Sync To Gallery": "مزامنة مع المعرض",
          "General Settings": "الإعدادات العامة",
          "Yes": "نعم",
          "No": "لا ",
          'to exit?': "للخروج؟",
          'Are you sure want': 'هل أنت متأكد أنك تريد',
          "Cleared cookies": "تم مسح ملفات تعريف الارتباط",
          "Cache Cleared": "تم مسح ذاكرة التخزين المؤقت",
          "Browser History Cleared": "تم مسح سجل المتصفح",
          "Clear cookies": "مسح ملفات تعريف الارتباط",
          "Trending": "الشائع",
          "Finish": "ينهي",
          "Next": "التالي",
          "Finished": "انتهى",
          "How to Download": "كيفية تحميل",
          "No History": "لا تاريخ",
          "3D": "3D",
          "Minimalism": "تقليلية",
          "City": "مدينة",
          "Cars": "سيارات",
          "Animals": "الحيوانات",
          "Anime": "أنيمي",
          "Flowers": "زهور",
          "Saved": "أنقذ",
          "Videos": "أشرطة فيديو",
          "Images": "الصور",
          "Enter Url here": "أدخل عنوان URL هنا",
          "Search": "يبحث",
          "Enter user name or paste profile URL":
              "أدخل اسم المستخدم أو الصق عنوان URL للملف الشخصي",
          "AD": "إعلان",
          "Video Download": "تنزيل الفيديو",
          "Paste": "معجون",
          "Direct Link Downloader": "برنامج تحميل برابط مباشر",
          "Vimeo": "فيميو",
          "TikTok": "تيك توك",
          "Twitter / X": "تويتر / اكس",
          "Instagram": "انستغرام",
          "Facebook": "فيسبوك",
          "Social Sites Downloader": "تحميل المواقع الاجتماعية",
          "Search Engine": "محرك البحث",
          "/storage/emulated/0/VideoDownloader/Download":
              "/storage/emulated/0/VideoDownloader/Download",
          "Download location": "موقع التنزيل",
          "Clear browser history": "مسح سجل المتصفح",
          "Clear Cache": "مسح ذاكرة التخزين المؤقت",
          "Google": "جوجل",
          "Recommended": "مُستَحسَن",
          "Save your passwords": "احفظ كلمات المرور الخاصة بك",
          "off": "عن",
          "on": "على",
          "Block Ads": "إعلانات كتلة",
          "Browser": "المتصفح",
          "Download with Wi-Fi only when turned on":
              "قم بالتنزيل باستخدام Wi-Fi فقط عند تشغيله",
          "Settings": "إعدادات",
          "Download": "تحميل",
          "Data Saving Mode": "وضع حفظ البيانات",
          "Tab": "فاتورة غير مدفوعة",
          "Progress": "تقدم",
          "Folder": "مجلد",
          "Video Downloader": "تنزيل الفيديو",
          "Continue": "يكمل",
          "Select Your Language": "اختر لغتك",
          "Search or paste profile URL":
              "ابحث عن عنوان URL للملف الشخصي أو الصقه",
          "Download Story, Post & Video": "تحميل القصة، مشاركة",
          "WhatsApp Status Downloader": "تنزيل حالة الواتس اب",
          "Download Whatsapp Stories & Status": "تحميل قصص واتس اب",
          "Wallpaper Downloader": "تنزيل خلفيات",
          "Download Varity of Wallpapers": "تحميل مجموعة متنوعة من الخلفيات",
          "Remove Ads": "ازالة الاعلانات",
          "Download everything without Ads": "قم بتنزيل كل شيء بدون إعلانات"
        },
        'en_bengali': {
          "Whatsapp":"হোয়াটসঅ্যাপ",
          "default": "ডিফল্ট",
          "Language Options": "ভাষার বিকল্প",
          'Privacy Policy': "গোপনীয়তা নীতি",
          "Feedback": "প্রতিক্রিয়া",
          'Help': "সাহায্য",
          "Sync To Gallery": "গ্যালারিতে সিঙ্ক করুন",
          "General Settings": "সাধারণ সেটিংস",
          "Yes": "হ্যা হ্যা",
          "No": "না",
          'to exit?': "প্রস্থান করতে?",
          'Are you sure want': 'আপনি কি নিশ্চিত চান',
          "Cleared cookies": "ক্লিয়ারড কুকিজ",
          "Cache Cleared": "ক্যাশে সাফ করা হয়েছে",
          "Browser History Cleared": "ব্রাউজার ইতিহাস সাফ করা হয়েছে",
          "Clear cookies": "কুকিজ সাফ করুন",
          "Trending": "চলমান",
          "Finish": "শেষ করুন",
          "Next": "পরবর্তী",
          "Finished": "সমাপ্ত",
          "How to Download": "ডাউনলোড করতে কিভাবে",
          "No History": "কোন ইতিহাস নেই",
          "3D": "জেডডি",
          "Minimalism": "মিনিমালিজম",
          "City": "শহর",
          "Cars": "গাড়ি",
          "Animals": "প্রাণী",
          "Anime": "এনিমে",
          "Flowers": "ফুল",
          "Saved": "সংরক্ষিত",
          "Videos": "ভিডিও",
          "Images": "ছবি",
          "Enter Url here": "এখানে Url লিখুন",
          "Search": "অনুসন্ধান করুন",
          "Enter user name or paste profile URL":
              "ব্যবহারকারীর নাম লিখুন বা প্রোফাইল UR পেস্ট করুনL",
          "AD": "বিজ্ঞাপন",
          "Video Download": "ভিডিও ডাউনলোড",
          "Paste": "পেস্ট করুন",
          "Direct Link Downloader": "ডাইরেক্ট লিংক ডাউনলোডার",
          "Vimeo": "ভিমিও",
          "TikTok": "টিক টক",
          "Twitter / X": "টুইটার/এক্স",
          "Instagram": "ইনস্টাগ্রাম",
          "Facebook": "ফেসবুক",
          "Social Sites Downloader": "সামাজিক সাইট ডাউনলোডার",
          "Search Engine": "খোঁজ যন্ত্র",
          "/storage/emulated/0/VideoDownloader/Download":
              "/storage/emulated/0/VideoDownloader/Download",
          "Download location": "অবস্থান ডাউনলোড করুন",
          "Clear browser history": "ব্রাউজারের ইতিহাস সাফ করুন",
          "Clear Cache": "ক্যাশে সাফ করুন",
          "Google": "গুগল",
          "Recommended": "প্রস্তাবিত",
          "Save your passwords": "আপনার পাসওয়ার্ড সংরক্ষণ করুন",
          "off": "বন্ধ",
          "on": "চালু",
          "Block Ads": "বিজ্ঞাপন ব্লক করুন",
          "Browser": "Browser",
          "Download with Wi-Fi only when turned on":
              "চালু থাকলেই Wi-Fi দিয়ে ডাউনলোড করুন",
          "Settings": "সেটিংস",
          "Download": "ডাউনলোড করুন",
          "Data Saving Mode": "ডেটা সেভিং মোড",
          "Tab": "ট্যাব",
          "Progress": "অগ্রগতি",
          "Folder": "ফোল্ডার",
          "Video Downloader": "ভিডিও ডাউনলোডার",
          "Continue": "চালিয়ে যান",
          "Select Your Language": "আপনার ভাষা নির্বাচন করুন",
          "Search or paste profile URL": "প্রোফাইল URL অনুসন্ধান বা পেস্ট করুন",
          "Download Story, Post & Video": "গল্প, পোস্ট এবং ভিডিও ডাউনলোড করুন",
          "WhatsApp Status Downloader": "হোয়াটসঅ্যাপ স্ট্যাটাস ডাউনলোডার",
          "Download Whatsapp Stories & Status":
              "Whatsapp গল্প এবং স্ট্যাটাস ডাউনলোড করুন",
          "Wallpaper Downloader": "ওয়ালপেপার ডাউনলোডার",
          "Download Varity of Wallpapers":
              "ওয়ালপেপারের বৈচিত্র্য ডাউনলোড করুন",
          "Remove Ads": "বিজ্ঞাপন সরান",
          "Download everything without Ads":
              "বিজ্ঞাপন ছাড়াই সবকিছু ডাউনলোড করুন"
        },
        'en_dutch': {
          "default": "standaard",
          "Language Options": "Taalopties",
          'Privacy Policy': "Privacybeleid",
          "Feedback": "Feedback",
          'Help': "Help",
          "Sync To Gallery": "Synchroniseren met",
          "General Settings": "Algemene instellingen",
          "Yes": "Ja",
          "No": "Nee",
          'to exit?': "'om af te sluiten?",
          'Are you sure want': 'Weet je het zeker',
          "Cleared cookies": "Cookies gewist",
          "Cache Cleared": "Cache gewist",
          "Browser History Cleared": "Browsergeschiedenis gewist",
          "Clear cookies": "Cookies wissen",
          "Trending": "Populair",
          "Finish": "Afgerond",
          "Next": "Volgende",
          "Finished": "Afgerond",
          "How to Download": "Hoe te downloaden",
          "No History": "Geen geschiedenis",
          "3D": "3D",
          "Minimalism": "Minimalisme",
          "City": "Stad",
          "Cars": "Auto's",
          "Animals": "Animals",
          "Anime": "Dieren",
          "Flowers": "Bloemen",
          "Saved": "Opgeslagen",
          "Videos": "Videos",
          "Images": "Afbeeldingen",
          "Enter Url here": "Voer hier de URL in",
          "Search": "Zoekopdracht",
          "Enter user name or paste profile URL":
              "Voer de gebruikersnaam in of plak de profiel-URL",
          "AD": "AD",
          "Video Download": "Video downloaden",
          "Paste": "Plakken",
          "Direct Link Downloader": "Directe link-downloader",
          "Vimeo": "Vimeo",
          "TikTok": "TikTok",
          "Twitter / X": "Twitter / X",
          "Instagram": "Instagram",
          "Facebook": "Facebook",
          "Social Sites Downloader": "Downloader voor sociale sites",
          "Search Engine": "Zoekmachine",
          "/storage/emulated/0/VideoDownloader/Download":
              "/storage/geëmuleerd/0/VideoDownloader/Download",
          "Download location": "Locatie downloaden",
          "Clear browser history": "Wis browsergeschiedenis",
          "Clear Cache": "Cache wissen",
          "Google": "Googlen",
          "Recommended": "Recommended",
          "Save your passwords": "Bewaar uw wachtwoorden",
          "off": "uit",
          "on": "op",
          "Block Ads": "Blokkeer advertenties",
          "Browser": "Browser",
          "Download with Wi-Fi only when turned on":
              "Alleen downloaden met Wi-Fi wanneer ingeschakeld",
          "Settings": "Instellingen",
          "Download": "Downloaden",
          "Data Saving Mode": "Gegevensbesparende modus",
          "Tab": "Tab",
          "Progress": "Voortgang",
          "Folder": "Map",
          "Video Downloader": "Video Downloader",
          "Continue": "Doorgaan",
          "Select Your Language": "Selecteer je taal",
          "Search or paste profile URL": "Zoek of plak de profiel-URL",
          "Download Story, Post & Video": "Ddownload verhaal, bericht en video",
          "WhatsApp Status Downloader": "WhatsApp Status Downloader",
          "Download Whatsapp Stories & Status":
              "Download WhatsApp-verhalen en status",
          "Wallpaper Downloader": "Achtergrond downloader",
          "Download Varity of Wallpapers":
              "Download een verscheidenheid aan achtergronden",
          "Remove Ads": "Verwijder advertenties",
          "Download everything without Ads":
              "Download alles zonder advertenties"
        },
        'en_finnish': {
            "Whatsapp":"Whatsapp",
          "default": "oletus",
          "Language Options": "Language Options",
          'Privacy Policy': "Tietosuojakäytäntö",
          "Feedback": "Palaute",
          'Help': "Apua",
          "Sync To Gallery": "Synkronoi galleriaan",
          "General Settings": "Yleiset asetukset",
          "Yes": "Kyllä",
          "No": "Ei ",
          'to exit?': "poistumaan?",
          'Are you sure want': 'Oletko varma, että haluat',
          "Cleared cookies": "Poistettu evästeet",
          "Cache Cleared": "Välimuisti tyhjennetty",
          "Browser History Cleared": "Selainhistoria tyhjennetty",
          "Clear cookies": "Poista evästeet",
          "Trending": "Trendaavat",
          "Finish": "Suorittaa loppuun",
          "Next": "Seuraava",
          "Finished": "Valmis",
          "How to Download": "Kuinka ladata",
          "No History": "Ei historiaa",
          "3D": "3D",
          "Minimalism": "Minimalismi",
          "City": "Kaupunki",
          "Cars": "Autot",
          "Animals": "Eläimet",
          "Anime": "Anime",
          "Flowers": "Kukat",
          "Saved": "Tallennettu",
          "Videos": "Videot",
          "Images": "Kuvat",
          "Enter Url here": "Kirjoita URL tähän",
          "Search": "Hae",
          "Enter user name or paste profile URL":
              "Anna käyttäjänimi tai liitä profiilin URL-osoite",
          "AD": "ILMOITUS",
          "Video Download": "Videon lataus",
          "Paste": "Liitä",
          "Direct Link Downloader": "Suora linkki latausohjelma",
          "Vimeo": "Vimeo",
          "TikTok": "TikTok",
          "Twitter / X": "Twitter / X",
          "Instagram": "Instagram",
          "Facebook": "Facebook",
          "Social Sites Downloader": "sosiaalisten sivustojen latausohjelma",
          "Search Engine": "Hakukone",
          "/storage/emulated/0/VideoDownloader/Download":
              "/storage/emulated/0/VideoDownloader/Download",
          "Download location": "Lataa sijainti",
          "Clear browser history": "Tyhjennä selainhistoria",
          "Clear Cache": "Tyhjennä välimuisti",
          "Google": "Google",
          "Recommended": "Suositeltava",
          "Save your passwords": "Tallenna salasanasi",
          "off": "vinossa",
          "on": "päällä",
          "Block Ads": "Estä mainokset",
          "Browser": "Selain",
          "Download with Wi-Fi only when turned on":
              "Lataa Wi-Fi-yhteydellä vain, kun se on päällä",
          "Settings": "asetukset",
          "Download": "ladata",
          "Data Saving Mode": "Tiedonsäästötila",
          "Tab": "Tab",
          "Progress": "Edistyminen",
          "Folder": "Kansio",
          "Video Downloader": "Video Downloader",
          "Continue": "Jatkaa",
          "Select Your Language": "Valitse kieli",
          "Search or paste profile URL": "Etsi tai liitä profiilin URL-osoite",
          "Download Story, Post & Video": "Lataa tarina, post",
          "WhatsApp Status Downloader": "whatsapp-tilan latausohjelma",
          "Download Whatsapp Stories & Status": "Lataa Whatsapp Stories",
          "Wallpaper Downloader": "Taustakuvan latausohjelma",
          "Download Varity of Wallpapers": "Lataa erilaisia ​​taustakuvia",
          "Remove Ads": "Poista mainokset",
          "Download everything without Ads": "Lataa kaikki ilman mainoksia"
        },
        'en_french': {
            "Whatsapp":"Whatsapp",
          "default": "par défaut",
          "Language Options": "Options de langue",
          'Privacy Policy': "Politique de confidentialité",
          "Feedback": "Commentaires",
          'Help': "À l'aide",
          "Sync To Gallery": "Synchroniser avec la galerie",
          "General Settings": "Paramètres généraux",
          "Yes": "Oui ",
          "No": "Non",
          'to exit?': "sortir?",
          'Are you sure want': 'Etes-vous sûr de vouloir',
          "Cleared cookies": "Cookies effacés",
          "Cache Cleared": "Cache vidé",
          "Browser History Cleared": "Historique du navigateur effacé",
          "Clear cookies": "Effacer les cookies",
          "Trending": "Tendance",
          "Finish": "Finition",
          "Next": "Suivant",
          "Finished": "Fini",
          "How to Download": "Comment télécharger",
          "No History": "Pas d'historique",
          "3D": "3D",
          "Minimalism": "Minimalisme",
          "City": "Ville",
          "Cars": "Voitures",
          "Animals": "Animaux",
          "Anime": "Anime",
          "Flowers": "Fleurs",
          "Saved": "Enregistré",
          "Videos": "Vidéos",
          "Images": "Images",
          "Enter Url here": "Entrez l'URL ici",
          "Search": "Recherche",
          "Enter user name or paste profile URL":
              "Entrez le nom d'utilisateur ou collez l'URL du profil",
          "AD": "ANNONCE",
          "Video Download": "Téléchargement vidéo",
          "Paste": "Pâte",
          "Direct Link Downloader": "Téléchargeur de lien direct",
          "Vimeo": "Viméo",
          "TikTok": "TIC Tac",
          "Twitter / X": "Twitter/X",
          "Instagram": "Instagram",
          "Facebook": "Facebook",
          "Social Sites Downloader": "Téléchargeur de sites sociaux",
          "Search Engine": "Moteur de recherche",
          "/storage/emulated/0/VideoDownloader/Download":
              "/stockage/emulated/0/VideoDownloader/Download",
          "Download location": "Emplacement de téléchargement",
          "Clear browser history": "Effacer l'historique du navigateur",
          "Clear Cache": "Vider le cache",
          "Google": "Google",
          "Recommended": "Recommandé",
          "Save your passwords": "Enregistrez vos mots de passe",
          "off": "désactivé",
          "on": "sur",
          "Block Ads": "Bloquer les publicités",
          "Browser": "Navigateur",
          "Download with Wi-Fi only when turned on":
              "Téléchargez avec Wi-Fi uniquement lorsqu'il est activé",
          "Settings": "Paramètres",
          "Download": "Télécharger",
          "Data Saving Mode": "Mode d'économie de données",
          "Tab": "Languette",
          "Progress": "Progrès",
          "Folder": "Dossier",
          "Video Downloader": "Téléchargeur de vidéo",
          "Continue": "Continuer",
          "Select Your Language": "Choisissez votre langue",
          "Search or paste profile URL": "Rechercher ou coller l'URL du profil",
          "Download Story, Post & Video": "Télécharger l'histoire, publier",
          "WhatsApp Status Downloader": "Téléchargeur de statut WhatsApp",
          "Download Whatsapp Stories & Status":
              "Téléchargez des histoires WhatsApp",
          "Wallpaper Downloader": "Téléchargeur de fond d'écran",
          "Download Varity of Wallpapers":
              "Téléchargez une variété de fonds d'écran",
          "Remove Ads": "Supprimez la pub",
          "Download everything without Ads": "Téléchargez tout sans publicité"
        },
        'en_german': {
            "Whatsapp":"Whatsapp",
          "default": "default",
          "Language Options": "Sprachoptionen",
          'Privacy Policy': "Datenschutzerklärung",
          "Feedback": "Feedback",
          'Help': "Hilfe",
          "Sync To Gallery": "Mit Galerie synchronisieren",
          "General Settings": "Allgemeine Einstellungen",
          "Yes": "ja",
          "No": "Nein",
          'to exit?': "zum Verlassen?",
          'Are you sure want': 'Willst du wirklich',
          "Cleared cookies": "Gelöschte Cookies",
          "Cache Cleared": "Cache geleert",
          "Browser History Cleared": "Browserverlauf gelöscht",
          "Clear cookies": "Cookies löschen",
          "Trending": "Im Trend",
          "Finish": "Beenden",
          "Next": "Nächste",
          "Finished": "Fertig",
          "How to Download": "Wie downloadet man das",
          "No History": "Keine Geschichte",
          "3D": "3D",
          "Minimalism": "Minimalismus",
          "City": "Stadt",
          "Cars": "Autos",
          "Animals": "Tiere",
          "Anime": "Anime",
          "Flowers": "Blumen",
          "Saved": "Gerettet",
          "Videos": "Videos",
          "Images": "Bilder",
          "Enter Url here": "Geben Sie hier die URL ein",
          "Search": "Search",
          "Enter user name or paste profile URL":
              "Geben Sie den Benutzernamen ein oder fügen Sie die Profil-URL ein",
          "AD": "ANZEIGE",
          "Video Download": "VVideo herunterladen",
          "Paste": "Paste",
          "Direct Link Downloader": "Direktlink-Downloader",
          "Vimeo": "Vimeo",
          "TikTok": "Tick ​​Tack",
          "Twitter / X": "Twitter / X",
          "Instagram": "Instagram",
          "Facebook": "Facebook",
          "Social Sites Downloader": "Downloader für soziale Websites",
          "Search Engine": "Such maschine",
          "/storage/emulated/0/VideoDownloader/Download":
              "/storage/emulated/0/VideoDownloader/Download",
          "Download location": "Speicherort herunterladen",
          "Clear browser history": "Browserverlauf löschen",
          "Clear Cache": "Cache leeren",
          "Google": "Google",
          "Recommended": "Empfohlen",
          "Save your passwords": "Speichern Sie Ihre Passwörter",
          "off": "aus",
          "on": "An",
          "Block Ads": "Werbung blockieren",
          "Browser": "Browser",
          "Download with Wi-Fi only when turned on":
              "Laden Sie nur mit WLAN herunter, wenn es eingeschaltet ist",
          "Settings": "Einstellungen",
          "Download": "Herunterladen",
          "Data Saving Mode": "Datensparmodus",
          "Tab": "Tab",
          "Progress": "Fortschritt",
          "Folder": "Ordner",
          "Video Downloader": "Video Downloader",
          "Continue": "Weitermachen",
          "Select Your Language": "Wähle deine Sprache",
          "Search or paste profile URL": "Profil-UR suchen oder einfügen",
          "Download Story, Post & Video":
              "Laden Sie Story, Beitrag und Video herunter",
          "WhatsApp Status Downloader": "WhatsApp Status Downloader",
          "Download Whatsapp Stories & Status":
              "Laden Sie WhatsApp-Geschichten und -Status herunter",
          "Wallpaper Downloader": "Wallpaper Downloader",
          "Download Varity of Wallpapers":
              "Laden Sie verschiedene Hintergrundbilder herunter",
          "Remove Ads": "Anzeigen entfernen",
          "Download everything without Ads":
              "Laden Sie alles ohne Werbung herunter"
        },
        'en_hindi': {
          "Whatsapp": "व्हाट्सएप",
          "default": "डिफ़ॉल्ट",
          "Language Options": "भाषा विकल्प",
          'Privacy Policy': "गोपनीयता नीति",
          "Feedback": "जानकारी देना",
          'Help': "मदद",
          "Sync To Gallery": "गैलरी से सिंक करें",
          "General Settings": "सामान्य सेटिंग",
          "Yes": "हां",
          "No": "नहीं ",
          'to exit?': "बाहर निकलने के लिए?'",
          'Are you sure want': 'क्या आप वाकई चाहते हैं',
          "Cleared cookies": "कुकीज़ साफ़ की गईं",
          "Cache Cleared": "कैश साफ़ किया गया",
          "Browser History Cleared": "ब्राउज़र इतिहास साफ़ किया गया",
          "Clear cookies": "कुकी साफ़ करें",
          "Trending": "रुझान",
          "Finish": "खत्म करना",
          "Next": "अगला",
          "Finished": "खत्म",
          "How to Download": "कैसे डाउनलोड करें",
          "No History": "कोई इतिहास नहीं",
          "3D": "3डी",
          "Minimalism": "अतिसूक्ष्मवाद",
          "City": "शहर",
          "Cars": "कारें",
          "Animals": "जानवरों",
          "Anime": "एनिमे",
          "Flowers": "पुष्प",
          "Saved": "बचाया",
          "Videos": "वीडियो",
          "Images": "इमेजिस",
          "Enter Url here": "यहां यूआरएल दर्ज करें",
          "Search": "खोज",
          "Enter user name or paste profile URL":
              "उपयोगकर्ता नाम दर्ज करें या प्रोफ़ाइल URL चिपकाएँ",
          "AD": "विज्ञापन",
          "Video Download": "वीडियो डाउनलोड",
          "Paste": "पेस्ट करें",
          "Direct Link Downloader": "डायरेक्ट लिंक डाउनलोडर",
          "Vimeo": "Vimeo",
          "TikTok": "टिक टॉक",
          "Twitter / X": "ट्विटर/एक्स",
          "Instagram": "Instagram",
          "Facebook": "फेसबुक",
          "Social Sites Downloader": "सोशल साइट्स डाउनलोडर",
          "Search Engine": "खोज इंजन",
          "/storage/emulated/0/VideoDownloader/Download":
              "/भंडारण/अनुकरण/0/वीडियोडाउनलोडर/डाउनलोड",
          "Download location": "स्थान डाउनलोड करें",
          "Clear browser history": "ब्राउज़र इतिहास साफ़ करें",
          "Clear Cache": "कैश को साफ़ करें",
          "Google": "गूगल",
          "Recommended": "अनुशंसित",
          "Save your passwords": "अपने पासवर्ड सहेजें",
          "off": "बंद",
          "on": "पर",
          "Block Ads": "विज्ञापन अवरोधित करें",
          "Browser": "ब्राउज़र",
          "Download with Wi-Fi only when turned on":
              "वाई-फाई चालू होने पर ही डाउनलोड करें",
          "Settings": "समायोजन",
          "Download": "डाउनलोड करना",
          "Data Saving Mode": "डेटा सेविंग मोड",
          "Tab": "टैब",
          "Progress": "प्रगति",
          "Folder": "फ़ोल्डर",
          "Video Downloader": "वीडियो डाउनलोडर",
          "Continue": "जारी रखना",
          "Select Your Language": "अपनी भाषा का चयन करें",
          "Search or paste profile URL": "प्रोफ़ाइल URL खोजें या चिपकाएँ",
          "Download Story, Post & Video": "कहानी, पोस्ट डाउनलोड करें",
          "WhatsApp Status Downloader": "व्हाट्सएप स्टेटस डाउनलोडर",
          "Download Whatsapp Stories & Status":
              "व्हाट्सएप स्टोरीज डाउनलोड करें",
          "Wallpaper Downloader": "वॉलपेपर डाउनलोडर",
          "Download Varity of Wallpapers":
              "विभिन्न प्रकार के वॉलपेपर डाउनलोड करें",
          "Remove Ads": "विज्ञापन हटाएँ",
          "Download everything without Ads":
              "विज्ञापनों के बिना सब कुछ डाउनलोड करें"
        },
        'en_indo': {
          "default": "bawaan",
          "Language Options": "Pilihan Bahasa",
          'Privacy Policy': "Kebijakan Privasi",
          "Feedback": "Umpan Balik",
          'Help': "Tolong",
          "Sync To Gallery": "Sinkronkan Ke Galeri",
          "General Settings": "Pengaturan Umum",
          "Yes": "Ya",
          "No": "Tidak",
          'to exit?': "keluar?",
          'Are you sure want': 'Apakah kamu yakin ingin',
          "Cleared cookies": "Cookie yang dibersihkan",
          "Cache Cleared": "Tembolok Dihapus",
          "Browser History Cleared": "Riwayat Peramban Dihapus",
          "Clear cookies": "Hapus cookie",
          "Trending": "Sedang tren",
          "Finish": "Menyelesaikan",
          "Next": "Berikutnya",
          "Finished": "Selesai",
          "How to Download": "Bagaimana cara mengunduh",
          "No History": "Tidak Ada Sejarah",
          "3D": "3D",
          "Minimalism": "Minimalisme",
          "City": "Kota",
          "Cars": "Mobil",
          "Animals": "Hewan",
          "Anime": "anime",
          "Flowers": "Bunga-bunga",
          "Saved": "Diselamatkan",
          "Videos": "Video",
          "Images": "Gambar-gambar",
          "Enter Url here": "Masukkan Url di sini",
          "Search": "Mencari",
          "Enter user name or paste profile URL":
              "Masukkan nama pengguna atau tempel URL profil",
          "AD": "IKLAN",
          "Video Download": "Unduh Video",
          "Paste": "Tempel",
          "Direct Link Downloader": "Pengunduh Tautan Langsung",
          "Vimeo": "Vimeo",
          "TikTok": "TIK tok",
          "Twitter / X": "Twitter / X",
          "Instagram": "Instagram",
          "Facebook": "Facebook",
          "Social Sites Downloader": "Pengunduh Situs Sosial",
          "Search Engine": "Mesin pencari",
          "/storage/emulated/0/VideoDownloader/Download":
              "/storage/emulated/0/VideoDownloader/Download",
          "Download location": "Lokasi pengunduhan",
          "Clear browser history": "Hapus riwayat peramban",
          "Clear Cache": "Hapus Tembolok",
          "Google": "Google",
          "Recommended": "Direkomendasikan",
          "Save your passwords": "Simpan kata sandi Anda",
          "off": "mati",
          "on": "pada",
          "Block Ads": "Blokir Iklan",
          "Browser": "Peramban",
          "Download with Wi-Fi only when turned on":
              "Unduh dengan Wi-Fi hanya saat dihidupkan",
          "Settings": "Pengaturan",
          "Download": "Unduh",
          "Data Saving Mode": "Mode Hemat Data",
          "Tab": "tab",
          "Progress": "Kemajuan",
          "Folder": "Map",
          "Video Downloader": "Pengunduh Video",
          "Continue": "Melanjutkan",
          "Select Your Language": "Pilih bahasamu",
          "Search or paste profile URL": "Cari atau tempel URL profil",
          "Download Story, Post & Video": "Unduh Cerita, Posting",
          "WhatsApp Status Downloader": "Pengunduh Status WhatsApp",
          "Download Whatsapp Stories & Status": "Unduh Cerita Whatsapp",
          "Wallpaper Downloader": "Pengunduh Wallpaper",
          "Download Varity of Wallpapers": "Unduh Variasi Wallpaper",
          "Remove Ads": "Hilangkan iklan",
          "Download everything without Ads": "Unduh semuanya tanpa Iklan"
        },
        'en_italian': {
            "Whatsapp":"Whatsapp",
          "default": "predefinito",
          "Language Options": "Opzioni lingua",
          'Privacy Policy': "politica sulla riservatezza",
          "Feedback": "Feedback",
          'Help': "Aiuto",
          "Sync To Gallery": "Sincronizza con la Galleria",
          "General Settings": "Impostazioni generali",
          "Yes": "si",
          "No": "No",
          'to exit?': "uscire?",
          'Are you sure want': 'Sei sicuro di volere',
          "Cleared cookies": "Cookie cancellati",
          "Cache Cleared": "Cache cancellata",
          "Browser History Cleared": "Cronologia del browser cancellata",
          "Clear cookies": "Biscotti puliti",
          "Trending": "Tendenza",
          "Finish": "Fine",
          "Next": "Prossimo",
          "Finished": "Finito",
          "How to Download": "Come scaricare",
          "No History": "Nessuna storia",
          "3D": "3D",
          "Minimalism": "Minimalismo",
          "City": "Città",
          "Cars": "Automobili",
          "Animals": "Animali",
          "Anime": "Anime",
          "Flowers": "Fiori",
          "Saved": "Salvato",
          "Videos": "Video",
          "Images": "immagini",
          "Enter Url here": "Inserisci l'URL qui",
          "Search": "Ricerca",
          "Enter user name or paste profile URL":
              "Inserisci il nome utente o incolla l'URL del profilo",
          "AD": "ANNO DOMINI",
          "Video Download": "Scarica video",
          "Paste": "Impasto",
          "Direct Link Downloader": "Downloader di collegamento diretto",
          "Vimeo": "Vimeo",
          "TikTok": "Tic toc",
          "Twitter / X": "Twitter/X",
          "Instagram": "Instagram",
          "Facebook": "Facebook",
          "Social Sites Downloader": "Downloader di siti social",
          "Search Engine": "Motore di ricerca",
          "/storage/emulated/0/VideoDownloader/Download":
              "/storage/emulated/0/VideoDownloader/Download",
          "Download location": "Scarica posizione",
          "Clear browser history": "Cancella la cronologia del browser",
          "Clear Cache": "Cancella cache",
          "Google": "Google",
          "Recommended": "Consigliato",
          "Save your passwords": "Salva le tue password",
          "off": "spento",
          "on": "SU",
          "Block Ads": "Blocca annunci",
          "Browser": "Navigatore",
          "Download with Wi-Fi only when turned on":
              "Scarica con Wi-Fi solo quando è acceso",
          "Settings": "Impostazioni",
          "Download": "Scaricamento",
          "Data Saving Mode": "Modalità di salvataggio dei dati",
          "Tab": "Tab",
          "Progress": "Progresso",
          "Folder": "Cartella",
          "Video Downloader": "Scaricatore di video",
          "Continue": "Continua",
          "Select Your Language": "Seleziona la tua lingua",
          "Search or paste profile URL": "Cerca o incolla l'URL del profilo",
          "Download Story, Post & Video": "Scarica Storia, pubblica",
          "WhatsApp Status Downloader": "Downloader dello stato di WhatsApp",
          "Download Whatsapp Stories & Status": "Scarica Storie di Whatsapp",
          "Wallpaper Downloader": "Scaricatore di sfondi",
          "Download Varity of Wallpapers": "Scarica varietà di sfondi",
          "Remove Ads": "Rimuovere gli annunci",
          "Download everything without Ads": "Scarica tutto senza pubblicità"
        },
        'en_japenes': {
            "Whatsapp":"Whatsapp",
          "default": "デフォルト",
          "Language Options": "言語オプション",
          'Privacy Policy': "プライバシーポリシー",
          "Feedback": "フィードバック",
          'Help': "助けて",
          "Sync To Gallery": "ギャラリーに同期",
          "General Settings": "「一般設定」",
          "Yes": "はいはい",
          "No": "「いいえ」",
          'to exit?': "'終了しますか?",
          'Are you sure want': '「本当に欲しいですか」',
          "Cleared cookies": "Cookieをクリアしました",
          "Cache Cleared": "キャッシュがクリアされました",
          "Browser History Cleared": "ブラウザ履歴が消去されました",
          "Clear cookies": "クッキーを消す",
          "Trending": "トレンド",
          "Finish": "仕上げる",
          "Next": "次",
          "Finished": "終了した",
          "How to Download": "ダウンロードする方法",
          "No History": "履歴はありません",
          "3D": "3D",
          "Minimalism": "ミニマリズム",
          "City": "市",
          "Cars": "車",
          "Animals": "動物",
          "Anime": "アニメ",
          "Flowers": "フラワーズ",
          "Saved": "保存されました",
          "Videos": "動画",
          "Images": "画像",
          "Enter Url here": "ここに URL を入力してください",
          "Search": "検索",
          "Enter user name or paste profile URL":
              "ユーザー名を入力するか、プロフィールの URL を貼り付けてください",
          "AD": "広告",
          "Video Download": "ビデオのダウンロード",
          "Paste": "ペースト",
          "Direct Link Downloader": "ダイレクトリンクダウンローダー",
          "Vimeo": "ヴィメオ",
          "TikTok": "チクタク",
          "Twitter / X": "ツイッター / ×",
          "Instagram": "インスタグラム",
          "Facebook": "フェイスブック",
          "Social Sites Downloader": "ソーシャル サイト ダウンローダー",
          "Search Engine": "検索エンジン",
          "/storage/emulated/0/VideoDownloader/Download":
              "/storage/emulated/0/VideoDownloader/ダウンロード",
          "Download location": "ダウンロード場所",
          "Clear browser history": "ブラウザ履歴をクリアする",
          "Clear Cache": "キャッシュの消去",
          "Google": "グーグル",
          "Recommended": "推奨",
          "Save your passwords": "パスワードを保存する",
          "off": "オフ",
          "on": "の上",
          "Block Ads": "広告をブロックする",
          "Browser": "ブラウザ",
          "Download with Wi-Fi only when turned on": "Wi-Fiがオンになっている場合のみダウンロード",
          "Settings": "設定",
          "Download": "ダウンロード",
          "Data Saving Mode": "データ節約モード",
          "Tab": "タブ",
          "Progress": "進捗",
          "Folder": "フォルダ",
          "Video Downloader": "ビデオダウンローダー",
          "Continue": "続く",
          "Select Your Language": "あなたが使う言語を選んでください",
          "Search or paste profile URL": "プロフィール URL を検索または貼り付けます",
          "Download Story, Post & Video": "ストーリーのダウンロード、投稿",
          "WhatsApp Status Downloader": "WhatsApp ステータス ダウンローダー",
          "Download Whatsapp Stories & Status": "Whatsapp ストーリーをダウンロード",
          "Wallpaper Downloader": "壁紙ダウンローダー",
          "Download Varity of Wallpapers": "さまざまな壁紙をダウンロード",
          "Remove Ads": "広告を削除",
          "Download everything without Ads": "広告なしですべてをダウンロード"
        },
        'en_english': {
          "Whatsapp":"Whatsapp",
          "default": "default",
          "Language Options": "Language Options",
          'Privacy Policy': "Privacy Policy",
          "Feedback": "Feedback",
          'Help': "Help",
          "Sync To Gallery": "Sync To Gallery",
          "General Settings": "General Settings",
          "Yes": "Yes",
          "No": "No",
          'to exit?': "to exit?",
          'Are you sure want': 'Are you sure want',
          "Cleared cookies": "Cleared cookies",
          "Cache Cleared": "Cache Cleared",
          "Browser History Cleared": "Browser History Cleared",
          "Clear cookies": "Clear cookies",
          "Trending": "Trending",
          "Finish": "Finish",
          "Next": "Next",
          "Finished": "Finished",
          "How to Download": "How to Download",
          "No History": "No History",
          "3D": "3D",
          "Minimalism": "Minimalism",
          "City": "City",
          "Cars": "Cars",
          "Animals": "Animals",
          "Anime": "Anime",
          "Flowers": "Flowers",
          "Saved": "Saved",
          "Videos": "Videos",
          "Images": "Images",
          "Enter Url here": "Enter Url here",
          "Search": "Search",
          "Enter user name or paste profile URL":
              "Enter user name or paste profile URL",
          "AD": "AD",
          "Video Download": "Video Download",
          "Paste": "Paste",
          "Direct Link Downloader": "Direct Link Downloader",
          "Vimeo": "Vimeo",
          "TikTok": "TikTok",
          "Twitter / X": "Twitter / X",
          "Instagram": "Instagram",
          "Facebook": "Facebook",
          "Social Sites Downloader": "Social Sites Downloader",
          "Search Engine": "Search Engine",
          "/storage/emulated/0/VideoDownloader/Download":
              "/storage/emulated/0/VideoDownloader/Download",
          "Download location": "Download location",
          "Clear browser history": "Clear browser history",
          "Clear Cache": "Clear Cache",
          "Google": "Google",
          "Recommended": "Recommended",
          "Save your passwords": "Save your passwords",
          "off": "off",
          "on": "on",
          "Block Ads": "Block Ads",
          "Browser": "Browser",
          "Download with Wi-Fi only when turned on":
              "Download with Wi-Fi only when turned on",
          "Settings": "Settings",
          "Download": "Download",
          "Data Saving Mode": "Data Saving Mode",
          "Tab": "Tab",
          "Progress": "Progress",
          "Folder": "Folder",
          "Video Downloader": "Video Downloader",
          "Continue": "Continue",
          "Select Your Language": "Select Your Language",
          "Search or paste profile URL": "Search or paste profile URL",
          "Download Story, Post & Video": "Download Story, Post & Video",
          "WhatsApp Status Downloader": "WhatsApp Status Downloader",
          "Download Whatsapp Stories & Status":
              "Download Whatsapp Stories & Status",
          "Wallpaper Downloader": "Wallpaper Downloader",
          "Download Varity of Wallpapers": "Download Varity of Wallpapers",
          "Remove Ads": "Remove Ads",
          "Download everything without Ads": "Download everything without Ads"
        },
      };
}
